package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Colors for Default theme
 * M3 Expressive colors generated by Material Theme Builder
 * https://goo.gle/material-theme-builder-web
 *
 * Key colors:
 * Primary #2979FF
 * Secondary #2979FF
 * Tertiary #47A84A
 * Neutral #919094
 *
 * Updated for M3 Expressive:
 * - Lebih vibrant pada primary/secondary
 * - Surface containers lebih berjenjang
 * - Warna tertiary lebih hidup untuk badge download
 */
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFADC6FF),
        onPrimary = Color(0xFF002E6E),
        primaryContainer = Color(0xFF0044A3),
        onPrimaryContainer = Color(0xFFD8E2FF),
        inversePrimary = Color(0xFF1A5CD6),
        secondary = Color(0xFFADC6FF), // Unread badge
        onSecondary = Color(0xFF002E6E), // Unread badge text
        secondaryContainer = Color(0xFF0044A3), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFFD8E2FF), // Navigation bar selector icon
        tertiary = Color(0xFF72DD6E), // Downloaded badge - lebih vibrant
        onTertiary = Color(0xFF003A00), // Downloaded badge text
        tertiaryContainer = Color(0xFF005200),
        onTertiaryContainer = Color(0xFF8EFB89),
        background = Color(0xFF111318),
        onBackground = Color(0xFFE2E2E9),
        surface = Color(0xFF111318),
        onSurface = Color(0xFFE2E2E9),
        surfaceVariant = Color(0xFF1C1B23), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFC5C6D2),
        surfaceTint = Color(0xFFADC6FF),
        inverseSurface = Color(0xFFE2E2E9),
        inverseOnSurface = Color(0xFF111318),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFF8F909B),
        outlineVariant = Color(0xFF45464F),
        scrim = Color(0xFF000000),
        surfaceContainerLowest = Color(0xFF0C0E13),
        surfaceContainerLow = Color(0xFF191B20),
        surfaceContainer = Color(0xFF1C1B23), // Navigation bar background
        surfaceContainerHigh = Color(0xFF252429),
        surfaceContainerHighest = Color(0xFF2F2D35),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF1A5CD6),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFD8E2FF),
        onPrimaryContainer = Color(0xFF001945),
        inversePrimary = Color(0xFFADC6FF),
        secondary = Color(0xFF1A5CD6), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFD8E2FF), // Navigation bar selector pill & progress indicator
        onSecondaryContainer = Color(0xFF001945), // Navigation bar selector icon
        tertiary = Color(0xFF006E1C), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFF8EFB89),
        onTertiaryContainer = Color(0xFF002203),
        background = Color(0xFFFAF8FF),
        onBackground = Color(0xFF1A1B21),
        surface = Color(0xFFFAF8FF),
        onSurface = Color(0xFF1A1B21),
        surfaceVariant = Color(0xFFE4E1EC), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF46464F),
        surfaceTint = Color(0xFF1A5CD6),
        inverseSurface = Color(0xFF2F3036),
        inverseOnSurface = Color(0xFFF1F0F7),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF777680),
        outlineVariant = Color(0xFFC7C5D0),
        scrim = Color(0xFF000000),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF4F2FA),
        surfaceContainer = Color(0xFFEEECF4), // Navigation bar background
        surfaceContainerHigh = Color(0xFFE8E6EF),
        surfaceContainerHighest = Color(0xFFE3E1E9),
    )
}
